### ISSUE TITLE
[REQUEST] Works great but feature needed

### ISSUE THREAD

**Issue by MRNFN80** [toc-irc/jservices#4]
When nickname that's authorized to "RELEASE" the nickname after it's taken, should auto release and give that person the nickname upon /NICK <thatname> instead of just /msg name RELEASE

so when it reserves my nickname and I connect back and send NICK mrinfinity it'll auto release and give me the nickname.

Having issues with the eggdrops not being able to get their nicknames back as well

**Comment by MRNFN80** [comment]
I can possibly edit the webchats and eggdrops to send PRIVMSG $me RELEASE I may need to think on this

**Comment by realrasengan** [comment]
There is no way to catch the /NICK without modifying the ircd.
